Add ROOT to gnu builds
Details:

* While clang works, libc++ does not work with ROOT. Cmake logic takes
care of switching to libstdc++, the other libraries that are
preconfigured for clang/libc++ will most likely fail linking if ROOT is
built with libstdc++. So we don't test clang with ROOT in TeamCity.

* The Intel compiler fails to build ROOT on the TeamCity build agents
with the following error:

CMake Error at <tpl>/build/intel/root/src/root-build/PCRE-prefix/src/PCRE-stamp/PCRE-build-RELEASE.cmake:16 (message):
  Command failed: 2

   'make'

  See also

    <tpl>/build/intel/root/src/root-build/PCRE-prefix/src/PCRE-stamp/PCRE-build-*.log

In PCRE-build-err.log:

pcrecpp.cc(74): error #1358: declaration aliased to undefined entity "_ZN7pcrecpp2RE6no_argE"
    __attribute__((alias(USER_LABEL_PREFIX_STR "_ZN7pcrecpp2RE6no_argE")));

So we only enable ROOT with the gnu builds on TeamCity for now.